# installation:
# create: conda env create -f environment-eventdisplay.yml
# activate: conda activate v2dl3Eventdisplay
#
name: v2dl3Eventdisplay
channels:
  - astropy
  - conda-forge
dependencies:
  - astropy>=4.0
  - click
  - numpy>=1.13
  - pytest
  - python>=3.8
  - pyyaml
  - scipy
  - uproot
