name: v2dl3 
channels:
  - astropy
  - conda-forge
dependencies:
  - python>=3.5 
  - click 
  - numpy>=1.13 
  - astropy>=4.0
  - cython>=0.27
  - pkgconfig
  - uproot4
  - root_numpy
  - root
  - tqdm