name: v2dl3
channels:
  - astropy
  - conda-forge
dependencies:
  - astropy>=4.0
  - click
  - cython>=0.27
  - numpy>=1.13
  - pandas
  - pkgconfig
  - python>=3.8
  - pyyaml
  - root_numpy
  - scipy
  - tqdm
  - uproot
