# installation:
# create: conda env create -f environment.yml
# activate: conda activate v2dl3_examples
#
name: v2dl3_examples
channels:
  - astropy
  - conda-forge
dependencies:
  - astropy
  - iminuit
  - jupyter
  - jupyterlab
  - gammapy
  - matplotlib
